---
- name: MailWall構築
  gather_facts: no
  hosts: vagrant
  sudo: yes

  vars_files:
    - dedev.yml

  roles:
    - common
    - common/user
    - middleware/ntp
    - middleware/postfix
    - middleware/dovecot
    - application/rainloop
