---
- name: ダウンロード
  get_url:
    url=https://download.elasticsearch.org/logstash/logstash/packages/centos/logstash-1.4.2-1_2c0f5a1.noarch.rpm
    dest=/home/{{ user }}/src/logstash-1.4.2-1_2c0f5a1.noarch.rpm
  tags:
    - logstash

- name: インストール
  yum:
    name=/home/{{ user }}/src/logstash-1.4.2-1_2c0f5a1.noarch.rpm
    state=installed
  tags:
   - logstash

- name: サービス登録・起動
  service:
    name=logstash
    state=started
    enabled=true
  tags:
    - logstash
